# ABOUTME: Typst preamble template for British stage play formatting.
# ABOUTME: Provides configurable font, margins, page size, and dialogue indent.
package OrgPlay::TypstTemplate;

use strict;
use warnings;
use utf8;

our $VERSION = '0.1.0';

# Returns the Typst preamble string with placeholders substituted.
sub preamble {
    my ($class, %opts) = @_;

    my $font              = $opts{font}              // 'New Computer Modern';
    my $font_size         = $opts{font_size}         // '12pt';
    my $margin            = $opts{margin}            // '25mm';
    my $page              = $opts{page}              // 'a4';
    my $indent            = $opts{indent}            // '4em';
    my $dialogue_spacing  = $opts{dialogue_spacing}  // '1em';
    my $direction_spacing = $opts{direction_spacing}  // '1em';
    my $direction_italic  = $opts{direction_italic}  // 1;
    my $direction_center  = $opts{direction_center}  // 0;

    # Build stage direction body markup
    my $dir_open  = $direction_italic ? '_' : '';
    my $dir_close = $direction_italic ? ' _' : '';

    # Build stage direction — use set align() to scope centering within the function
    my $dir_align = $direction_center ? "\n  set align(center)" : '';

    return <<"TYPST";
// Generated by org-play-to-pdf
#set page(paper: "$page", margin: $margin, numbering: "1", number-align: center + bottom)
#set text(font: "$font", size: $font_size)
#set par(leading: 0.6em)

// Dialogue block — name inline with dialogue, hanging indent for continuation lines
// When a direction is present, it appears on the first line and dialogue on the next.
#let dialogue(name, direction: none, body) = {
  block(above: ${dialogue_spacing}, below: 0.2em)[
    #if direction != none [
      #box(width: ${indent})[#text(weight: "bold")[#name:]]_(#direction)_
      #block(inset: (left: ${indent}))[#body]
    ] else [
      #par(hanging-indent: ${indent})[
        #box(width: ${indent})[#text(weight: "bold")[#name:]]#body
      ]
    ]
  ]
}

// Stage direction
#let stage-direction(body) = {${dir_align}
  block(above: ${direction_spacing}, below: 0.6em)[
    ${dir_open}#body${dir_close}
  ]
}

// Act header
#let act-header(title) = {
  v(1.5em)
  align(center)[#text(size: 1.4em, weight: "bold")[#title]]
  v(0.8em)
}

// Scene header
#let scene-header(title) = {
  v(1em)
  text(size: 1.2em, weight: "bold")[#title]
  v(0.5em)
}

// Prop text (signs, placards)
#let prop-text(body) = {
  align(center)[#text(style: "italic", weight: "bold")[#body]]
}

TYPST
}

# Returns a Typst title page block.
sub title_page {
    my ($class, %opts) = @_;
    my $title    = $opts{title}    // '';
    my $subtitle = $opts{subtitle} // '';
    my $author   = $opts{author}   // '';

    return '' unless $title;

    my $out = <<"TYPST";
#align(center)[
  #v(30%)
  #text(size: 2em, weight: "bold")[$title]
TYPST

    if ($subtitle) {
        $out .= <<"TYPST";
  #v(0.5em)
  #text(size: 1.4em)[$subtitle]
TYPST
    }

    if ($author) {
        $out .= <<"TYPST";
  #v(1em)
  #text(size: 1.2em)[by $author]
TYPST
    }

    $out .= <<'TYPST';
]
#pagebreak()

TYPST

    return $out;
}

1;
