// Generated by First Folio.

// State readers used by page-header and page-footer format tokens.
// The initial value is empty so [part]/[chapter] render blank on pages preceding the first heading.
#let _folio_part_state_init = state("folio-current-part", "")
#let _folio_chapter_state_init = state("folio-current-chapter", "")

// A blank page macro used to satisfy folio.manuscript.{part,chapter}.blank-page-{before,after}.
// A weak pagebreak avoids doubling with an adjacent hard break; the empty page() scope removes
// numbering, header, and footer so the blank page is visually blank and unnumbered.
#let folio-blank-page() = {
  pagebreak(weak: true)
  page(numbering: none, header: none, footer: none)[]
}

#let folio-section(body) = {
  v(1.2em)
  align(left)[#text(
    font: "{{.Config.Folio.Manuscript.HeadingFont}}",
    size: {{.Config.Folio.Manuscript.HeadingFontSize}},
    weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
  )[#heading(level: 3, outlined: {{.Config.Folio.Manuscript.TOC.IncludeSections}})[#body]]]
  v(0.4em)
}

#let folio-part(first: false, body) = {
  state("folio-current-part").update(body)
  state("folio-current-chapter").update([])
  if not first and {{.Config.Folio.Manuscript.Part.PageBreakBefore}} {
    pagebreak()
  }
  align({{.Config.Folio.Manuscript.Part.Align}} + {{.PartVertical}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 1, outlined: {{.Config.Folio.Manuscript.TOC.IncludeParts}})[#body]
    ]
  ]
}

#let folio-chapter(first: false, body) = {
  state("folio-current-chapter").update(body)
  if not first and {{.Config.Folio.Manuscript.Chapter.PageBreakBefore}} {
    pagebreak()
  }
  v({{.ChapterPosition}})
  align({{.Config.Folio.Manuscript.Chapter.Align}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 2, outlined: {{.Config.Folio.Manuscript.TOC.IncludeChapters}})[#body]
    ]
  ]
  v({{.Config.Folio.Manuscript.Chapter.SpaceAfter}})
}

#let folio-scene-break() = {
  v(1em)
  align(center)[{{.SceneBreakMarker}}]
  v(1em)
}

#let folio-code(body) = {
  block(
    above: {{.Config.Folio.Manuscript.CodeBlock.SpaceBefore}},
    below: {{.Config.Folio.Manuscript.CodeBlock.SpaceAfter}},
  )[
    #text(
      font: "{{.Config.Folio.Manuscript.MonoFont}}",
      size: {{.Config.Folio.Manuscript.MonoFontSize}},
      weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
    )[#body]
  ]
}

#show list: it => {
  v({{.Config.Folio.Manuscript.List.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.List.SpaceAfter}})
}

#show enum: it => {
  v({{.Config.Folio.Manuscript.List.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.List.SpaceAfter}})
}

#show figure.where(kind: table): it => {
  v({{.Config.Folio.Manuscript.Table.SpaceBefore}})
  it
  v({{.Config.Folio.Manuscript.Table.SpaceAfter}})
}

#show strong: it => text(weight: "bold")[#it.body]
#show emph: it => text(style: "italic")[#it.body]

#show raw.where(block: true): it => block(
  above: {{.Config.Folio.Manuscript.CodeBlock.SpaceBefore}},
  below: {{.Config.Folio.Manuscript.CodeBlock.SpaceAfter}},
)[#text(
  font: "{{.Config.Folio.Manuscript.MonoFont}}",
  size: {{.Config.Folio.Manuscript.MonoFontSize}},
  weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
)[#it]]

#show raw.where(block: false): it => text(
  font: "{{.Config.Folio.Manuscript.MonoFont}}",
  size: {{.Config.Folio.Manuscript.MonoFontSize}},
  weight: "{{.Config.Folio.Manuscript.MonoFontWeight}}",
)[#it]

#set page(
  {{if .PageSpec.Custom}}width: {{.PageSpec.Width}}, height: {{.PageSpec.Height}},{{else}}paper: "{{.PageSpec.Named}}",{{end}}
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: {{if .Config.Folio.Manuscript.TitlePage.PageNumber}}"1"{{else}}none{{end}},
)

#set text(
  font: "{{.Config.Folio.Manuscript.Font}}",
  size: {{.Config.Folio.Manuscript.FontSize}},
  weight: "{{.Config.Folio.Manuscript.FontWeight}}",
)

{{if and (not .IsUS) .Config.Folio.Manuscript.TitlePage.Enabled}}
#set page(
  footer: [
    #grid(
      columns: (1fr, 1fr, 1fr),
      align: (left, {{.FooterGroupAlignExpr}}, right),
      [
        {{if .Config.Folio.Manuscript.TitlePage.IncludeVersion}}#text(font: "{{.Config.Folio.Manuscript.VersionFont}}", size: {{.Config.Folio.Manuscript.VersionFontSize}}, weight: "{{.Config.Folio.Manuscript.VersionFontWeight}}")[{{.Meta.Version}}]{{end}}
      ],
      [
        {{if .Config.Folio.Manuscript.TitlePage.IncludeWordCount}}#text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[
          #if "{{.Meta.WordCount}}" != "" [{{.Meta.WordCount}}]
        ]{{end}}
      ],
      [
        {{if .Config.Folio.Manuscript.TitlePage.IncludeDate}}#text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}}, weight: "{{.Config.Folio.Manuscript.DateFontWeight}}")[{{.Meta.Date}}]{{end}}
      ],
    )
  ],
)
{{end}}

{{if .Config.Folio.Manuscript.TitlePage.Enabled}}
{{if .HasContact}}#place({{if .ContactAlignExpr}}{{.ContactAlignExpr}}{{else}}top + left{{end}}, float: true)[
  #stack(
    dir: ttb,
    spacing: 0.25em,
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeContactName .Meta.ContactName}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.ContactName}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeAddress .Meta.Address}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Address}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludePhone .Meta.Phone}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Phone}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeEmail .Meta.Email}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Email}}]],{{end}}
    {{if and .Config.Folio.Manuscript.TitlePage.IncludeWebsite .Meta.Website}}[#text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}}, weight: "{{.Config.Folio.Manuscript.ContactFontWeight}}")[{{.Meta.Website}}]],{{end}}
  )
]
{{end}}
{{if .TitleAlignExpr}}#place({{.TitleAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeTitle}}
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  {{end}}
]{{end}}
{{if .SubtitleAlignExpr}}#place({{.SubtitleAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeSubtitle}}#if "{{.Meta.Subtitle}}" != "" [
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      weight: "{{.Config.Folio.Manuscript.SubtitleFontWeight}}",
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]{{end}}
]{{end}}
{{if .AuthorAlignExpr}}#place({{.AuthorAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeAuthor}}#if "{{.Meta.Author}}" != "" [
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}}, weight: "{{.Config.Folio.Manuscript.AuthorFontWeight}}")[{{if .Meta.AuthorAttribution}}{{.Meta.AuthorAttribution}} {{end}}{{.Meta.Author}}]
  ]{{end}}
]{{end}}
{{if .DateAlignExpr}}#place({{.DateAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeDate}}#text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}}, weight: "{{.Config.Folio.Manuscript.DateFontWeight}}")[{{.Meta.Date}}]{{end}}
]{{end}}
{{if .WordCountAlignExpr}}#place({{.WordCountAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeWordCount}}#text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[{{.Meta.WordCount}}]{{end}}
]{{end}}
{{if .VersionAlignExpr}}#place({{.VersionAlignExpr}})[
  {{if .Config.Folio.Manuscript.TitlePage.IncludeVersion}}#text(font: "{{.Config.Folio.Manuscript.VersionFont}}", size: {{.Config.Folio.Manuscript.VersionFontSize}}, weight: "{{.Config.Folio.Manuscript.VersionFontWeight}}")[{{.Meta.Version}}]{{end}}
]{{end}}
#align({{.TitleBlockAlignExpr}})[
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeTitle (not .TitleAlignExpr)}}
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  {{end}}
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeSubtitle (not .SubtitleAlignExpr)}}#if "{{.Meta.Subtitle}}" != "" [
    #v(1em)
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      weight: "{{.Config.Folio.Manuscript.SubtitleFontWeight}}",
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]{{end}}
  {{if and .Config.Folio.Manuscript.TitlePage.IncludeAuthor (not .AuthorAlignExpr)}}#if "{{.Meta.Author}}" != "" [
    #v(2em)
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}}, weight: "{{.Config.Folio.Manuscript.AuthorFontWeight}}")[{{if .Meta.AuthorAttribution}}{{.Meta.AuthorAttribution}} {{end}}{{.Meta.Author}}]
  ]{{end}}
]

{{if .IsUS}}
{{if .Config.Folio.Manuscript.TitlePage.IncludeWordCount}}#if "{{.Meta.WordCount}}" != "" [
  #place(bottom + center, float: true)[
    #text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}}, weight: "{{.Config.Folio.Manuscript.WordCountFontWeight}}")[{{.Meta.WordCount}}]
  ]
]{{end}}
{{end}}

{{if .Config.Folio.Manuscript.TOC.PageBreakBefore}}#pagebreak(){{end}}
{{end}}

{{if .Config.Folio.Manuscript.TOC.Enabled}}
#set page(numbering: none, footer: none)
#text(
  font: "{{.Config.Folio.Manuscript.TOC.HeadingFont}}",
  size: {{.Config.Folio.Manuscript.TOC.HeadingFontSize}},
  weight: "{{.Config.Folio.Manuscript.TOC.HeadingFontWeight}}",
)[{{.Config.Folio.Manuscript.TOC.Title}}]
#v(1em)
#text(font: "{{.Config.Folio.Manuscript.TOC.Font}}", size: {{.Config.Folio.Manuscript.TOC.FontSize}}, weight: "{{.Config.Folio.Manuscript.TOC.FontWeight}}")[
  #set par(leading: {{.Config.Folio.Manuscript.TOC.LineSpacing}})
  #show outline.entry: it => block(
    above: if it.level == 1 { {{.Config.Folio.Manuscript.TOC.PartGapBefore}} } else { 0pt },
    below: 0.5em,
  )[
    #if it.level == 1 and {{.Config.Folio.Manuscript.TOC.PartBold}} {
      strong[#it]
    } else {
      it
    }
  ]
  #outline(title: none)
]
#pagebreak()
{{end}}

#counter(page).update(1)
#set text(
  top-edge: 0.8em,
  bottom-edge: -0.2em,
)
#set par(
  first-line-indent: {{.Config.Folio.Manuscript.ParagraphIndent}},
  spacing: {{.Spacing}},
  leading: {{.Leading}},
)
#set page(
  {{if .PageSpec.Custom}}width: {{.PageSpec.Width}}, height: {{.PageSpec.Height}},{{else}}paper: "{{.PageSpec.Named}}",{{end}}
  {{if .Config.Folio.Manuscript.PageHeader.Enabled}}margin: (
    top: {{.Config.Folio.Manuscript.PageHeader.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageHeader.ContentPaddingAfter}},
    {{if .PageFooterEnabled}}bottom: {{.Config.Folio.Manuscript.PageFooter.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}
    {{if .GutterActive}}inside: {{.Config.Folio.Manuscript.Margin}} + {{.Gutter}},
    outside: {{.Config.Folio.Manuscript.Margin}},{{else}}rest: {{.Config.Folio.Manuscript.Margin}},{{end}}
  ),
  header-ascent: {{.Config.Folio.Manuscript.PageHeader.ContentPaddingAfter}},
  {{if .PageFooterEnabled}}footer-descent: {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}{{else}}margin: (
    {{if .PageFooterEnabled}}bottom: {{.Config.Folio.Manuscript.PageFooter.DistanceFromEdge}} + {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}
    {{if .GutterActive}}inside: {{.Config.Folio.Manuscript.Margin}} + {{.Gutter}},
    outside: {{.Config.Folio.Manuscript.Margin}},{{else}}rest: {{.Config.Folio.Manuscript.Margin}},{{end}}
  ),
  {{if .PageFooterEnabled}}footer-descent: {{.Config.Folio.Manuscript.PageFooter.ContentPaddingAfter}},{{end}}{{end}}
  numbering: none,
  {{if .PageFooterEnabled}}footer: {{if .FooterAlignIsPair}}context {{end}}align({{.FooterAlignExpr}})[
    #text(
      font: "{{.Config.Folio.Manuscript.PageFooter.Font}}",
      size: {{.Config.Folio.Manuscript.PageFooter.FontSize}},
      weight: "{{.Config.Folio.Manuscript.PageFooter.FontWeight}}",
    )[{{.Footer}}]
  ],{{else}}footer: none,{{end}}
  {{if .Config.Folio.Manuscript.PageHeader.Enabled}}header: {{if .HeaderAlignIsPair}}context {{end}}align({{.HeaderAlignExpr}})[
    #pad(right: calc.max({{.Config.Folio.Manuscript.PageHeader.DistanceFromEdge}} - {{.Config.Folio.Manuscript.Margin}}, 0pt) + 0.5em)[
      #text(
        font: "{{.Config.Folio.Manuscript.PageHeader.Font}}",
        size: {{.Config.Folio.Manuscript.PageHeader.FontSize}},
        weight: "{{.Config.Folio.Manuscript.PageHeader.FontWeight}}",
      )[{{.Header}}]
    ]
  ],{{else}}header: none,{{end}}
)

{{.Body}}
