// Generated by First Folio.

#let folio-para(body) = {
  block[
    #body
  ]
}

#let folio-section(body) = {
  v(1.2em)
  align(left)[#text(
    font: "{{.Config.Folio.Manuscript.HeadingFont}}",
    size: {{.Config.Folio.Manuscript.HeadingFontSize}},
    weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
  )[#body]]
  v(0.4em)
}

#let folio-part(first: false, body) = {
  if not first {
    pagebreak()
  }
  align({{.Config.Folio.Manuscript.Part.Align}} + horizon)[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 1)[#body]
    ]
  ]
}

#let folio-chapter(first: false, body) = {
  if not first {
    pagebreak()
  }
  v(30%)
  align({{.Config.Folio.Manuscript.Chapter.Align}})[
    #text(
      font: "{{.Config.Folio.Manuscript.HeadingFont}}",
      size: {{.Config.Folio.Manuscript.HeadingFontSize}},
      weight: "{{.Config.Folio.Manuscript.HeadingFontWeight}}",
    )[
      #heading(level: 2)[#body]
    ]
  ]
  v({{.Config.Folio.Manuscript.Chapter.SpaceAfter}})
}

#let folio-scene-break() = {
  v(1em)
  align(center)[\* \* \*]
  v(1em)
}

#let folio-code(body) = {
  block[
    #text(font: "{{.Config.Folio.Manuscript.MonoFont}}", size: {{.Config.Folio.Manuscript.MonoFontSize}})[#body]
  ]
}

#set page(
  paper: "{{.Config.Folio.Manuscript.Page}}",
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: none,
)

#set text(font: "{{.Config.Folio.Manuscript.Font}}", size: {{.Config.Folio.Manuscript.FontSize}})
#set par(
  first-line-indent: {{.Config.Folio.Manuscript.ParagraphIndent}},
  spacing: {{.Config.Folio.Manuscript.ParagraphSpacing}},
  leading: {{.Config.Folio.Manuscript.LineSpacing}}em,
)

{{if .IsUS}}
#grid(
  columns: (1fr, 1fr),
  align: (left, right),
  [
    #text(font: "{{.Config.Folio.Manuscript.ContactFont}}", size: {{.Config.Folio.Manuscript.ContactFontSize}})[
      {{.Meta.Author}}
      #if "{{.Meta.Address}}" != "" [#linebreak(){{.Meta.Address}}]
      #if "{{.Meta.Phone}}" != "" [#linebreak(){{.Meta.Phone}}]
      #if "{{.Meta.Email}}" != "" [#linebreak(){{.Meta.Email}}]
      #if "{{.Meta.Website}}" != "" [#linebreak(){{.Meta.Website}}]
    ]
  ],
  [
    #if "{{.Meta.WordCount}}" != "" [
      #text(font: "{{.Config.Folio.Manuscript.WordCountFont}}", size: {{.Config.Folio.Manuscript.WordCountFontSize}})[{{.Meta.WordCount}} words]
    ]
  ],
)
#align(center + horizon)[
{{else}}
#set page(
  footer: align({{.Config.Folio.Manuscript.TitlePage.FooterAlign}})[
    #text(font: "{{.Config.Folio.Manuscript.DateFont}}", size: {{.Config.Folio.Manuscript.DateFontSize}})[
      #if "{{.Meta.Version}}" != "" [{{.Meta.Version}}]
      #if "{{.Meta.Version}}" != "" and "{{.Meta.Date}}" != "" [ | ]
      #if "{{.Meta.Date}}" != "" [{{.Meta.Date}}]
      #if ("{{.Meta.Version}}" != "" or "{{.Meta.Date}}" != "") and "{{.Meta.WordCount}}" != "" [ | ]
      #if "{{.Meta.WordCount}}" != "" [{{.Meta.WordCount}} words]
    ]
  ],
)
#align(center + horizon)[
{{end}}
  #text(
    font: "{{.Config.Folio.Manuscript.TitleFont}}",
    size: {{.Config.Folio.Manuscript.TitleFontSize}},
    weight: "{{.Config.Folio.Manuscript.TitleFontWeight}}",
  )[{{.Meta.Title}}]
  #if "{{.Meta.Subtitle}}" != "" [
    #v(1em)
    #text(
      font: "{{.Config.Folio.Manuscript.SubtitleFont}}",
      size: {{.Config.Folio.Manuscript.SubtitleFontSize}},
      style: "{{.Config.Folio.Manuscript.SubtitleFontStyle}}",
    )[{{.Meta.Subtitle}}]
  ]
  #if "{{.Meta.Author}}" != "" [
    #v(2em)
    #text(font: "{{.Config.Folio.Manuscript.AuthorFont}}", size: {{.Config.Folio.Manuscript.AuthorFontSize}})[{{.Meta.AuthorAttribution}} {{.Meta.Author}}]
  ]
]

#pagebreak()

{{if .Config.Folio.Manuscript.TOC.Enabled}}
#set page(numbering: none)
#text(
  font: "{{.Config.Folio.Manuscript.TOC.HeadingFont}}",
  size: {{.Config.Folio.Manuscript.TOC.HeadingFontSize}},
  weight: "{{.Config.Folio.Manuscript.TOC.HeadingFontWeight}}",
)[{{.Config.Folio.Manuscript.TOC.Title}}]
#v(1em)
#text(font: "{{.Config.Folio.Manuscript.TOC.Font}}", size: {{.Config.Folio.Manuscript.TOC.FontSize}})[
  #set par(leading: 0.15em)
  #outline(title: none)
]
#pagebreak()
{{end}}

#counter(page).update(1)
#set page(
  paper: "{{.Config.Folio.Manuscript.Page}}",
  margin: {{.Config.Folio.Manuscript.Margin}},
  numbering: none,
  header: align(right)[
    #text(
      font: "{{.Config.Folio.Manuscript.PageHeader.Font}}",
      size: {{.Config.Folio.Manuscript.PageHeader.FontSize}},
      weight: "{{.Config.Folio.Manuscript.PageHeader.FontWeight}}",
    )[{{.Header}}]
  ],
)

{{.Body}}
